sudo: required
dist: trusty
services: docker

before_install:
  - chmod +x .ci/docker-run.sh && ./.ci/docker-run.sh
  - sudo sh -c 'echo "deb [arch=amd64] https://apt-mo.trafficmanager.net/repos/dotnet-release/ trusty main" > /etc/apt/sources.list.d/dotnetdev.list'
  - sudo apt-key adv --keyserver apt-mo.trafficmanager.net --recv-keys 417A0893
  - sudo apt-get update
  - sudo apt-get install -y dotnet-dev-1.0.0-preview2-003121

script:
  - dotnet restore
  - dotnet test tests/MySqlConnector.Tests --configuration Release
  - echo 'Executing tests with No Compression, No SSL' && cp tests/SideBySide.New/config.json.example tests/SideBySide.New/config.json && dotnet test tests/SideBySide.New --configuration Release
  - echo 'Executing tests with Compression, No SSL' && cp .ci/config.compression.json tests/SideBySide.New/config.json && dotnet test tests/SideBySide.New --configuration Release
  - echo 'Executing tests with No Compression, SSL' && cp .ci/config.ssl.json tests/SideBySide.New/config.json && dotnet test tests/SideBySide.New --configuration Release
  - echo 'Executing tests with Compression, SSL' && cp .ci/config.compression+ssl.json tests/SideBySide.New/config.json && dotnet test tests/SideBySide.New --configuration Release

after_script:
  - chmod +x .ci/build-docs.sh && ./.ci/build-docs.sh

