version: 1.0.{build}
image: Visual Studio 2015
configuration: Release
services:
  - mysql
install:
- cmd: |-
    dotnet restore
build_script:
- cmd: |-
    dotnet build src\MySqlConnector --configuration Release
    dotnet build tests\SideBySide.New --configuration Release
before_test:
- cmd: |-
    copy tests\SideBySide.New\config.json.example tests\SideBySide.New\config.json
    "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql.exe" -u root --password=Password12! < .ci\init.sql
test_script:
- cmd: |-
    dotnet test tests\MySqlConnector.Tests --configuration Release
    dotnet test tests\SideBySide.New --configuration Release
