services:
- mysql
build_script:
- ps: .\.ci\build.ps1
before_test:
- cmd: |-
    "C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql.exe" -u root --password=Password12! < .ci\server\init.sql
test_script:
- ps: .\.ci\test.ps1
after_test:
- cmd: dotnet pack src\MySqlConnector\MySqlConnector.csproj --configuration Release
notifications:
- provider: Slack
  incoming_webhook:
    secure: SRJ5fYQE4tvelyqeX3Lkv0gXta3O2pl4/+wNaqmqmcFkmYBe+U31T5YCGhipBOVhHBIZLevihOJZ78sFVJrmAFV5bHgtX/VPIKEXN+7ytis=
deploy:
  - provider: NuGet
    api_key:
      secure: fLUem5pVBjrrXi52uwp796QP2j5enZsTv36p4dGtW1OOSxWcQYFdb2Z4IZaaHPQZ
    artifact: src\MySqlConnector\bin\Release\*.nupkg
    skip_symbols: true
    on:
      appveyor_repo_tag: true
